### ISSUE TITLE
Cannot allocate memory

### ISSUE THREAD

**Issue by rbrtmrtn** [datamade/csvdedupe#41]
I'm trying to use csvdedupe against a dataset of about 800k records. After `blocking` is complete I encounter an `OSError: Cannot allocate memory`. This is using Python 3.4 on an Ubuntu AWS instance with 7.5 GB of memory.

```
INFO:dedupe.blocking:820000, 260.8973972 seconds
INFO:dedupe.api:0 blocks
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/opa_parse/bin/csvdedupe", line 11, in <module>
    sys.exit(launch_new_instance())
  File "/home/ubuntu/.virtualenvs/opa_parse/lib/python3.4/site-packages/csvdedupe/csvdedupe.py", line 162, in launch_new_instance
    d.main()
  File "/home/ubuntu/.virtualenvs/opa_parse/lib/python3.4/site-packages/csvdedupe/csvdedupe.py", line 134, in main
    threshold = deduper.threshold(data_d, recall_weight=self.recall_weight)
  File "/home/ubuntu/.virtualenvs/opa_parse/lib/python3.4/site-packages/dedupe/api.py", line 204, in threshold
    return self.thresholdBlocks(blocked_pairs, recall_weight)
  File "/home/ubuntu/.virtualenvs/opa_parse/lib/python3.4/site-packages/dedupe/api.py", line 70, in thresholdBlocks
    self.num_cores)['score']
  File "/home/ubuntu/.virtualenvs/opa_parse/lib/python3.4/site-packages/dedupe/core.py", line 220, in scoreDuplicates
    [process.start() for process in map_processes]
  File "/home/ubuntu/.virtualenvs/opa_parse/lib/python3.4/site-packages/dedupe/core.py", line 220, in <listcomp>
    [process.start() for process in map_processes]
  File "/usr/lib/python3.4/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.4/multiprocessing/context.py", line 212, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/lib/python3.4/multiprocessing/context.py", line 267, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.4/multiprocessing/popen_fork.py", line 21, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.4/multiprocessing/popen_fork.py", line 70, in _launch
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
```

When I run it with Python 2.7.6 it runs significantly slower, gets through about 670,000 rows and throws `Segmentation fault (core dumped)`.

Is this just a problem with the specs of my machine? Is 7.5 GB just not enough memory for a 93 MB, 800k row file?

Thanks in advance for any help!

**Comment by AbsoluteResults** [comment]
I'm getting this same issue. I've tried on a list of 100K rows, then 40K, then 20K then finally to 10K to get it to work so I could see results. Just about anything more than 10K rows throws a Segmentation fault during blocking. It is only a 2GB machine but I thought 10K would be well within reach.

**Comment by fgregg** [comment]
2gb is pretty small. Take a look at the mysql-example for avoiding this
memory problem while blocking https://github.com/datamade/dedupe-examples

**Comment by fgregg** [comment]
@
