### ISSUE TITLE
Unhashable type error when destructive option is enabled

### ISSUE THREAD

**Issue by shre81** [datamade/csvdedupe#53]
Can't get my head around why this is happening. The write functions in the csvhelper.py appear to be similar but when I want to output just the unique records, I get an 'unhashable type: numpy.ndarray'. 

`Traceback (most recent call last):
  File "c:\python34\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python34\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python34\Scripts\csvdedupe.exe\__main__.py", line 9, in <module>
  File "c:\python34\lib\site-packages\csvdedupe\csvdedupe.py", line 148, in launch_new_instance
    d.main()
  File "c:\python34\lib\site-packages\csvdedupe\csvdedupe.py", line 137, in main
    write_function(clustered_dupes, self.input, output_file)
  File "c:\python34\lib\site-packages\csvdedupe\csvhelpers.py", line 107, in writeUniqueResults
    cluster_membership[record_id] = cluster_id
TypeError: unhashable type: 'numpy.ndarray'`

Anyone else face this issue? Any workarounds? Thanks

**Comment by fgregg** [comment]
I think this should fix your issue? https://github.com/datamade/csvdedupe/commit/fa3690a8f4c9d9f3de7e0a8f4d2c282ddc54a338

Can you clone from github and confirm?

**Comment by shre81** [comment]
Perfect. This solved it. Also, it helped me understand the code better.
