### ISSUE TITLE
TypeError: expected string or buffer

### ISSUE THREAD

**Issue by evandam** [datamade/csvdedupe#62]
I'm getting the following errors when trying to run csvdedupe with my own dataset. After following dedupe examples, I think it has to do with the preProcess function.
```
Traceback (most recent call last):
  File "/usr/app/anaconda/bin/csvdedupe", line 11, in <module>
    sys.exit(launch_new_instance())
  File "/usr/app/anaconda/lib/python2.7/site-packages/csvdedupe/csvdedupe.py", line 148, in launch_new_instance
    d.main()
  File "/usr/app/anaconda/lib/python2.7/site-packages/csvdedupe/csvdedupe.py", line 69, in main
    data_d = csvhelpers.readData(self.input, self.field_names)
  File "/usr/app/anaconda/lib/python2.7/site-packages/csvdedupe/csvhelpers.py", line 52, in readData
    clean_row = {k: preProcess(v) for (k, v) in row.items()}
  File "/usr/app/anaconda/lib/python2.7/site-packages/csvdedupe/csvhelpers.py", line 52, in <dictcomp>
    clean_row = {k: preProcess(v) for (k, v) in row.items()}
  File "/usr/app/anaconda/lib/python2.7/site-packages/csvdedupe/csvhelpers.py", line 29, in preProcess
    column = re.sub('  +', ' ', column)
  File "/usr/app/anaconda/lib/python2.7/re.py", line 155, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or buffer
```

Checking if the column is already None and casting it to a string first seems to solve the issue.

Thanks in advance!

**Comment by fgregg** [comment]
you have a malformed csv. We should be throwing an error.

**Comment by evandam** [comment]
My apologies! After looking through countless lines of the input file, I was missing the last column in my header row. Closing the issue. Thanks!
